#db_member表的触发器
DROP TRIGGER IF EXISTS DB_MEMBER_INS;
CREATE TRIGGER DB_MEMBER_INS
  BEFORE INSERT ON DB_MEMBER
  FOR EACH ROW SET NEW.lastModTime := CURRENT_TIMESTAMP,NEW.createDate:= CURRENT_TIMESTAMP;

DROP TRIGGER IF EXISTS DB_MEMBER_UPD;
CREATE TRIGGER DB_MEMBER_UPD
  BEFORE UPDATE ON DB_MEMBER
  FOR EACH ROW SET NEW.lastModTime := CURRENT_TIMESTAMP;


#db_login_trace表的触发器
DROP TRIGGER IF EXISTS DB_LOGIN_TRACE_INS;
CREATE TRIGGER DB_LOGIN_TRACE_INS
  BEFORE INSERT ON DB_LOGIN_TRACE
  FOR EACH ROW SET NEW.lastModTime := CURRENT_TIMESTAMP,NEW.createDate:= CURRENT_TIMESTAMP;

DROP TRIGGER IF EXISTS DB_LOGIN_TRACE_UPD;
CREATE TRIGGER DB_LOGIN_TRACE_UPD
  BEFORE UPDATE ON DB_LOGIN_TRACE
  FOR EACH ROW SET NEW.lastModTime := CURRENT_TIMESTAMP;
